### ISSUE TITLE
Ansi not working

### ISSUE THREAD

**Issue by craciu25yt** [AnAverageBeing/XDDOS#3]
![image](https://user-images.githubusercontent.com/48807342/181662750-e1b4cae3-d395-4f73-8f8c-8eef01d58417.png)
the ANSI colours don't work

**Comment by XDMEOW** [comment]
use console that support it

**Comment by XDMEOW** [comment]
![image](https://user-images.githubusercontent.com/84959276/181996784-814bff8a-7ac9-415b-8e9b-fbce755fd6df.png)
works for me

**Comment by craciu25yt** [comment]
> use console that support it

it was cmd so its supposed to work

**Comment by XDMEOW** [comment]
hmm try something like changing settings cuz it's works for Linux terminal and i tested in windows also works in command prompt

**Comment by AnAverageBeing** [comment]
Use -noansi in new jar to fix

**Comment by AnAverageBeing** [comment]
Hope this helped u
