### ISSUE TITLE
Low cps

### ISSUE THREAD

**Issue by Egra228** [AnAverageBeing/XDDOS#6]
Low cps in all method | internet 100mbit/s

![image](https://user-images.githubusercontent.com/56909385/188316612-36b22ff4-9780-4cfc-bb2b-3f93ccaa0c27.png)

**Comment by Egra228** [comment]
![image](https://user-images.githubusercontent.com/56909385/188316830-017a39de-8786-42a3-921c-78dfd76c3694.png)

**Comment by XDMEOW** [comment]
can u send the command u used

**Comment by Egra228** [comment]
![image](https://user-images.githubusercontent.com/56909385/191159079-7898f395-74d0-4ad5-bfcc-ee0c35211045.png)
BotJoiner
java -jar XDDOS.jar
manually entered)

**Comment by InfiniteCod3** [comment]
This seems more like a Proxy issue.

**Comment by InfiniteCod3** [comment]
or you are using a bad java version

**Comment by Egra228** [comment]
I don't know, I use it through my IP
2 java versions
![image](https://user-images.githubusercontent.com/56909385/192778347-5ec59f2f-941f-47b6-9e3c-7dfd79327699.png)

**Comment by InfiniteCod3** [comment]
are you running it on a windows machine?

**Comment by Egra228** [comment]
+ through ubuntu
![image](https://user-images.githubusercontent.com/56909385/192778740-6d4f204d-2c76-480d-bc20-686da619980e.png)

**Comment by InfiniteCod3** [comment]
basically through a vm?

**Comment by Egra228** [comment]
wsl

**Comment by Egra228** [comment]
I'll check it on my phone via termux

**Comment by AnAverageBeing** [comment]
Its problem with ur machine I get 5k cps with 4 cores vps
